services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - whatsapp-clone-network
    restart: unless-stopped
  keycloak:
    container_name: keycloak_wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - whatsapp-clone-network
    command:
      - "start-dev"

networks:
  whatsapp-clone-network:
    driver: bridge
volumes:
  postgres:
    driver: local