spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: ${JPA_HIBERNATE_FORMAT_SQL}
    flyway:
        enabled: false
    security:
        oauth2:
            resource-server:
                jwt:
                    issuer-uri: ${OAUTH2_JWT_ISSUER_URI}
    servlet:
        multipart:
            max-file-size: ${SERVLET_MULTIPART_MAX_FILE_SIZE}

application:
    file:
        uploads:
            media-output-path: ./uploads
    frontendUrl: ${FRONTEND_URL}